
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebBanHang.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Food
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Food()
    {

        this.FoodIngredients = new HashSet<FoodIngredient>();

        this.GioHangs = new HashSet<GioHang>();

        this.InvoiceDetails = new HashSet<InvoiceDetail>();

        this.OrderDetails = new HashSet<OrderDetail>();

    }


    public int FoodId { get; set; }

    public string FoodName { get; set; }

    public Nullable<int> CategoryId { get; set; }

    public Nullable<int> IngredientId { get; set; }

    public decimal Price { get; set; }

    public Nullable<decimal> Discount { get; set; }

    public Nullable<decimal> DiscountPrice { get; set; }

    public int Stock { get; set; }

    public string Description { get; set; }

    public string ImageURL { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public Nullable<bool> Status { get; set; }



    public virtual Category Category { get; set; }

    public virtual Ingredient Ingredient { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FoodIngredient> FoodIngredients { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GioHang> GioHangs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetail> OrderDetails { get; set; }

}

}
