
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebBanHang.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FoodIngredient
{

    public int FoodIngredientId { get; set; }

    public Nullable<int> FoodId { get; set; }

    public Nullable<int> IngredientId { get; set; }

    public int Quantity { get; set; }



    public virtual Food Food { get; set; }

    public virtual Ingredient Ingredient { get; set; }

}

}
