
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebBanHang.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GioHang
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GioHang()
    {

        this.GioHang_Topping = new HashSet<GioHang_Topping>();

    }


    public int GioHangID { get; set; }

    public int Id { get; set; }

    public int FoodId { get; set; }

    public int SoLuong { get; set; }

    public Nullable<int> SizeID { get; set; }

    public decimal TotalPrice { get; set; }



    public virtual Food Food { get; set; }

    public virtual User User { get; set; }

    public virtual Size Size { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GioHang_Topping> GioHang_Topping { get; set; }

}

}
