
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebBanHang.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GioHang_Topping
{

    public int GioHangToppingID { get; set; }

    public int GioHangID { get; set; }

    public int ToppingID { get; set; }



    public virtual GioHang GioHang { get; set; }

    public virtual Topping Topping { get; set; }

}

}
