
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebBanHang.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Ingredient
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ingredient()
    {

        this.Foods = new HashSet<Food>();

        this.FoodIngredients = new HashSet<FoodIngredient>();

        this.Warehouses = new HashSet<Warehouse>();

    }


    public int IngredientId { get; set; }

    public string IngredientName { get; set; }

    public int SoLuong { get; set; }

    public string PhanLoai { get; set; }

    public string ImageURL { get; set; }

    public System.DateTime LastUpdated { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Food> Foods { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FoodIngredient> FoodIngredients { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Warehouse> Warehouses { get; set; }

}

}
