
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebBanHang.Models
{

using System;
    using System.Collections.Generic;
    
public partial class InvoiceDetail
{

    public int InvoiceDetailId { get; set; }

    public Nullable<int> InvoiceId { get; set; }

    public Nullable<int> FoodId { get; set; }

    public int SoLuong { get; set; }

    public decimal Price { get; set; }



    public virtual Food Food { get; set; }

    public virtual Invoice Invoice { get; set; }

}

}
