
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebBanHang.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Invoice
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Invoice()
    {

        this.InvoiceDetails = new HashSet<InvoiceDetail>();

    }


    public int InvoiceId { get; set; }

    public Nullable<int> TableId { get; set; }

    public System.DateTime DateCheckIn { get; set; }

    public Nullable<System.DateTime> DateCheckOut { get; set; }

    public Nullable<int> TrangThai { get; set; }



    public virtual TableFood TableFood { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }

}

}
