

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebBanHang.Models
{

    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;


    public partial class WebAppDBEntities : DbContext
    {
        public WebAppDBEntities()
            : base("name=WebAppDBEntities")
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }


        public virtual DbSet<Account> Accounts { get; set; }

        public virtual DbSet<AccRole> AccRoles { get; set; }

        public virtual DbSet<Category> Categories { get; set; }

        public virtual DbSet<Food> Foods { get; set; }

        public virtual DbSet<FoodIngredient> FoodIngredients { get; set; }

        public virtual DbSet<GioHang> GioHangs { get; set; }

        public virtual DbSet<GioHang_Topping> GioHang_Topping { get; set; }

        public virtual DbSet<Ingredient> Ingredients { get; set; }

        public virtual DbSet<Invoice> Invoices { get; set; }

        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }

        public virtual DbSet<OrderDetail> OrderDetails { get; set; }

        public virtual DbSet<Order> Orders { get; set; }

        public virtual DbSet<OrderStatu> OrderStatus { get; set; }

        public virtual DbSet<PhuongThucThanhToan> PhuongThucThanhToans { get; set; }

        public virtual DbSet<Size> Sizes { get; set; }

        public virtual DbSet<Staff> Staffs { get; set; }

        public virtual DbSet<TableFood> TableFoods { get; set; }

        public virtual DbSet<Topping> Toppings { get; set; }

        public virtual DbSet<User> Users { get; set; }

        public virtual DbSet<Warehouse> Warehouses { get; set; }

        public virtual DbSet<DeliveryAddress> DeliveryAddresses { get; set; }

    }

}

