
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebBanHang.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OrderDetail
{

    public int OrderDetailId { get; set; }

    public int OrderId { get; set; }

    public int FoodId { get; set; }

    public Nullable<int> SizeId { get; set; }

    public Nullable<int> ToppingId { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }



    public virtual Food Food { get; set; }

    public virtual Order Order { get; set; }

    public virtual Size Size { get; set; }

    public virtual Topping Topping { get; set; }

}

}
