
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebBanHang.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Warehouse
{

    public int WarehouseId { get; set; }

    public Nullable<int> IngredientId { get; set; }

    public int SoLuong { get; set; }

    public System.DateTime DateUpdate { get; set; }



    public virtual Ingredient Ingredient { get; set; }

}

}
